pipeline {
    agent any
    environment{
        mysql_cred=credentials('db_pwd')
    }

   stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Roshani1812/docker-projects_todo.git'
            }
        }

        stage('Create Docker Network') {
            steps {
                script {
                    sh 'docker network create todo-app-network || true'
                }
            }
        }

        stage('Run MySQL Container') {
            steps {
                script {
                    sh '''
                    docker run -d --network todo-app-network --network-alias mysql \
                    -v todo-mysql-data:/var/lib/mysql \
                    -e MYSQL_ROOT_PASSWORD=db_pwd \
                    -e MYSQL_DATABASE=todos \
                    mysql:9.0
                    '''
                }
            }
        }

        stage('Build and Run Node.js App') {
            steps {
                script {
                    dir('todo-app') {
                        sh '''
                       
                        docker build -t todo-app:latest .
                        docker run -d --name todo-app -p 8091:3000 --network todo-app-network \
                        -e MYSQL_HOST=mysql \
                        -e MYSQL_USER=root \
                        -e MYSQL_PASSWORD=db_pwd \
                        -e MYSQL_DB=todos \
                        todo-app:latest sh -c "yarn install && yarn run dev"
                        '''
                    }
                }
            }
        }
        stage('Check App Status') {
            steps {
                script {
                    def appStatus = sh(script: 'docker inspect -f {{.State.Running}} todo-app', returnStdout: true).trim()
                    if (appStatus != 'true') {
                        error 'Application failed to start'
                    }
                }
            }
        }

    }

    post {
        always {
            script {
                sh 'docker stop todo-app || true'
                sh 'docker rm todo-app || true'
                sh 'docker rm mysql || true'
                sh 'docker network rm todo-app-network || true'
            }
        }
    }
}
